version: "1"
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./server:/app #Synchronise docker container with local change
      - /app/node_modules #Avoid re-copying local node_modules. Cache in volume.
